/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SpecialAbility = IDL.Record({
  'abilityName' : IDL.Text,
  'abilityDescription' : IDL.Text,
});
export const Stats = IDL.Record({
  'stealth' : IDL.Nat,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'specialRating' : IDL.Nat,
});
export const Character = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'country' : IDL.Text,
  'specialAbility' : SpecialAbility,
  'name' : IDL.Text,
  'countryFlag' : IDL.Text,
  'stats' : Stats,
});
export const PlayerRanking = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'rank' : IDL.Nat,
  'wins' : IDL.Nat,
  'playerName' : IDL.Text,
  'characterId' : IDL.Nat,
  'kills' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharacterById' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerRanking)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SpecialAbility = IDL.Record({
    'abilityName' : IDL.Text,
    'abilityDescription' : IDL.Text,
  });
  const Stats = IDL.Record({
    'stealth' : IDL.Nat,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'specialRating' : IDL.Nat,
  });
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'country' : IDL.Text,
    'specialAbility' : SpecialAbility,
    'name' : IDL.Text,
    'countryFlag' : IDL.Text,
    'stats' : Stats,
  });
  const PlayerRanking = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'rank' : IDL.Nat,
    'wins' : IDL.Nat,
    'playerName' : IDL.Text,
    'characterId' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharacterById' : IDL.Func([IDL.Nat], [IDL.Opt(Character)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerRanking)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };