/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : bigint,
  'bio' : string,
  'country' : string,
  'specialAbility' : SpecialAbility,
  'name' : string,
  'countryFlag' : string,
  'stats' : Stats,
}
export interface PlayerRanking {
  'gamesPlayed' : bigint,
  'rank' : bigint,
  'wins' : bigint,
  'playerName' : string,
  'characterId' : bigint,
  'kills' : bigint,
}
export interface SpecialAbility {
  'abilityName' : string,
  'abilityDescription' : string,
}
export interface Stats {
  'stealth' : bigint,
  'speed' : bigint,
  'strength' : bigint,
  'specialRating' : bigint,
}
export interface _SERVICE {
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getCharacterById' : ActorMethod<[bigint], [] | [Character]>,
  'getLeaderboard' : ActorMethod<[], Array<PlayerRanking>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];